language: java

sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

install: mvn install -DskipTests=true -Dgpg.skip=true

script: mvn verify -Dgpg.skip=true -Dmaven.javadoc.skip=true
